#ifndef MIXER_LANG_INTERFACE_FILESTREAM_HPP_INCLUDED
#define MIXER_LANG_INTERFACE_FILESTREAM_HPP_INCLUDED

#include "../src/lexer_filestream.hpp"

#endif // MIXER_LANG_INTERFACE_FILESTREAM_HPP_INCLUDED
