#ifndef MIXER_LANG_INTERFACE_CSTRSTREAM_HPP_INCLUDED
#define MIXER_LANG_INTERFACE_CSTRSTREAM_HPP_INCLUDED

#include "../src/lexer_cstrstream.hpp"

#endif // MIXER_LANG_INTERFACE_CSTRSTREAM_HPP_INCLUDED
